// =============================================================================
// Libmork — Pathfinder 2e Classes Catalog & Data
// =============================================================================

export interface Pf2eClassDefinition {
  key: string;
  name: string;
  keyAttribute: string;
  hpPerLevel: number;
  description: string;
  proficiencies: {
    weapons?: string[];
    armor?: string[];
    languages?: string[];
    tools?: string[];
  };
  initialItems: Array<{
    name: string;
    quantity: number;
    description?: string;
  }>;
  levels: Array<{
    level: number;
    hpBonus: number;
    manaBonus: number;
    attributeBonuses?: Record<string, number>;
    extraTrainedSkills?: number;
    advantages?: string[];
    skillsGranted?: string[];
    spellsGranted?: string[];
    description: string;
  }>;
}

function generateLevels(
  hpPerLevel: number,
  isSpellcaster: boolean,
  keyAttr: string,
  classFeaturesByLevel: Record<number, string[]>
): Pf2eClassDefinition["levels"] {
  const levels: Pf2eClassDefinition["levels"] = [];

  for (let lvl = 1; lvl <= 20; lvl++) {
    const features = classFeaturesByLevel[lvl] || [];
    const isAbilityBoostLevel = lvl === 5 || lvl === 10 || lvl === 15 || lvl === 20;
    const manaBonus = isSpellcaster ? (lvl === 1 ? 5 : 3) : 0;

    const attributeBonuses: Record<string, number> | undefined = isAbilityBoostLevel
      ? { [keyAttr]: 1 }
      : undefined;

    const descriptionParts: string[] = [];
    if (features.length > 0) {
      descriptionParts.push(`Habilidades: ${features.join(", ")}`);
    }
    if (isAbilityBoostLevel) {
      descriptionParts.push("Melhoria de Atributo (+1)");
    }
    if (lvl % 2 === 0) {
      descriptionParts.push("Talento de Classe & Talento de Perícia");
    } else if (lvl > 1) {
      descriptionParts.push("Aumento de Perícia & Talento Geral/Ancestral");
    }

    levels.push({
      level: lvl,
      hpBonus: hpPerLevel,
      manaBonus,
      attributeBonuses,
      extraTrainedSkills: lvl === 1 ? 3 : (lvl % 2 === 1 ? 1 : 0),
      advantages: features,
      description: descriptionParts.join(". "),
    });
  }

  return levels;
}

export const PF2E_CLASSES: Pf2eClassDefinition[] = [
  {
    key: "alchemist",
    name: "Alchemist",
    keyAttribute: "inteligencia",
    hpPerLevel: 8,
    description: "Mestre das ciências arcanas e reações químicas. Prepara elixires, bombas alquímicas, venenos e mutagênicos com precisão cirúrgica.",
    proficiencies: {
      weapons: ["Armas simples", "Bombas alquímicas"],
      armor: ["Armadura leve", "Defesa sem armadura"],
      languages: ["Comum", "Alquímico"],
      tools: ["Kit de alquimia", "Ferramentas de artesão"],
    },
    initialItems: [
      { name: "Kit de Alquimia Básico", quantity: 1, description: "Conjunto de tubos de ensaio, almofariz e reagentes." },
      { name: "Fórmula de Fogo Alquímico", quantity: 2, description: "Frasco com líquido inflamável." },
      { name: "Elixir de Vida Menor", quantity: 2, description: "Restaura pontos de vida quando consumido." },
      { name: "Adaga", quantity: 1, description: "Arma simples leve para defesa pessoal." },
    ],
    levels: generateLevels(8, false, "inteligencia", {
      1: ["Alquimia Infusa", "Campo de Pesquisa", "Fórmulas Alquímicas"],
      2: ["Talento de Alquimista"],
      3: ["Especialista em Alquimia", "Aumento de Perícia"],
      5: ["Especialista em Armas Simples", "Aprimoramento de Campo"],
      7: ["Alquimista Experiente", "Evasão"],
      9: ["Especialização de Alquimista", "Resistência Dobrada"],
      11: ["Alquimista Mestre", "Mestre em Fortitude"],
      13: ["Especialização Superior", "Armadura Leve Mestre"],
      15: ["Alquimista Notável", "Aprimoramento de Campo Superior"],
      17: ["Alquimista Lendário", "Grande Mutagênico"],
      19: ["Perfeição Alquímica"],
    }),
  },
  {
    key: "barbarian",
    name: "Barbarian",
    keyAttribute: "forca",
    hpPerLevel: 12,
    description: "Guerreiro movido pela fúria primal do combate. Converte cólera em poder devastador, resistência física sobre-humana e brutalidade implacável.",
    proficiencies: {
      weapons: ["Armas simples", "Armas marciais", "Ataques desarmados"],
      armor: ["Armadura leve", "Armadura média", "Defesa sem armadura"],
      languages: ["Comum"],
      tools: [],
    },
    initialItems: [
      { name: "Machado de Batalha", quantity: 1, description: "Arma marcial pesada capaz de desferir golpes devastadores." },
      { name: "Armadura de Couro Batido", quantity: 1, description: "Proteção leve e flexível." },
      { name: "Azagaias", quantity: 4, description: "Armas de arremesso para engajamento à distância." },
      { name: "Mochila de Aventureiro", quantity: 1, description: "Corda, tochas, rações e cantil." },
    ],
    levels: generateLevels(12, false, "forca", {
      1: ["Fúria Primal", "Instinto Bárbaro"],
      2: ["Talento de Bárbaro"],
      3: ["Fúria Aprimorada", "Especialização em Dano"],
      5: ["Especialista em Armas Marciais", "Ataque Brutal"],
      7: ["Instinto Superior", "Evasão de Fúria"],
      9: ["Fúria Crítica", "Firmeza Inabalável"],
      11: ["Mestre em Fortitude", "Fúria Poderosa"],
      13: ["Especialização Maior", "Armadura Média Mestre"],
      15: ["Fúria Indomável", "Grande Consciência"],
      17: ["Fúria Lendária", "Titã de Batalha"],
      19: ["Colosso Enfurecido"],
    }),
  },
  {
    key: "bard",
    name: "Bard",
    keyAttribute: "empatia",
    hpPerLevel: 8,
    description: "Erudito e artista que canaliza a magia oculta através de atuações musicais, poéticas e retórica inspiradora para apoiar aliados e confundir inimigos.",
    proficiencies: {
      weapons: ["Armas simples", "Florete", "Espada curta", "Chicote"],
      armor: ["Armadura leve", "Defesa sem armadura"],
      languages: ["Comum"],
      tools: ["Instrumento musical"],
    },
    initialItems: [
      { name: "Alaúde Artesanal", quantity: 1, description: "Instrumento de cordas finamente trabalhado para conjurar magia." },
      { name: "Florete", quantity: 1, description: "Arma leve e precisa para duelos." },
      { name: "Armadura de Couro", quantity: 1, description: "Armadura leve básica." },
      { name: "Bolsa de Componentes", quantity: 1, description: "Pós, ervas e cristais para magia." },
    ],
    levels: generateLevels(8, true, "empatia", {
      1: ["Composição Mágica", "Musa Bárdica", "Magia Oculta"],
      2: ["Talento de Bardo"],
      3: ["Magias de 2º Círculo", "Inspiração Aprimorada"],
      5: ["Magias de 3º Círculo", "Especialista em Armas Simples"],
      7: ["Magias de 4º Círculo", "Especialista em Conjuração Oculta"],
      9: ["Magias de 5º Círculo", "Grande Musa"],
      11: ["Magias de 6º Círculo", "Mestre em Vontade"],
      13: ["Magias de 7º Círculo", "Especialização Superior"],
      15: ["Magias de 8º Círculo", "Mestre em Conjuração Oculta"],
      17: ["Magias de 9º Círculo", "Sinfonia Heroica"],
      19: ["Magias de 10º Círculo / Conjurador Lendário"],
    }),
  },
  {
    key: "champion",
    name: "Champion",
    keyAttribute: "forca",
    hpPerLevel: 10,
    description: "Guerreiro sagrado jurado a uma causa divina. Porta escudo e armadura impenetráveis para proteger os fracos e punir transgressores.",
    proficiencies: {
      weapons: ["Armas simples", "Armas marciais", "Ataques desarmados"],
      armor: ["Todas as armaduras (Leve, Média, Pesada)", "Escudos", "Defesa sem armadura"],
      languages: ["Comum"],
      tools: ["Símbolo sagrado"],
    },
    initialItems: [
      { name: "Espada Longa", quantity: 1, description: "Arma marcial de uma mão clássica." },
      { name: "Escudo de Aço Pesado", quantity: 1, description: "Escudo reforçado para bloquear ataques pesados." },
      { name: "Cota de Malha", quantity: 1, description: "Armadura média de anéis entrelaçados." },
      { name: "Símbolo Sagrado de Prata", quantity: 1, description: "Canalizador divino." },
    ],
    levels: generateLevels(10, true, "forca", {
      1: ["Causa do Campeão", "Reação do Campeão", "Graça Divina"],
      2: ["Talento de Campeão"],
      3: ["Fidelidade Divina", "Aliado Divino"],
      5: ["Especialista em Armas Marciais", "Smite Sagrado"],
      7: ["Especialista em Armadura Pesada", "Proteção Resiliente"],
      9: ["Especialização de Campeão", "Aura Divina"],
      11: ["Mestre em Armadura Pesada", "Vontade Sagrada"],
      13: ["Mestre em Armas Marciais", "Especialização Maior"],
      15: ["Guardião Inabalável", "Graça Superior"],
      17: ["Lendário em Armadura", "Avatar da Devoção"],
      19: ["Herói do Julgamento"],
    }),
  },
  {
    key: "cleric",
    name: "Cleric",
    keyAttribute: "empatia",
    hpPerLevel: 8,
    description: "Canalizador devoto das bênçãos e milagres divinos. Cura ferimentos, bane mortos-vivos e fortalece aliados com o poder de sua divindade.",
    proficiencies: {
      weapons: ["Armas simples", "Arma favorecida da divindade"],
      armor: ["Defesa sem armadura", "Armadura leve (doutrina)", "Escudos"],
      languages: ["Comum"],
      tools: ["Símbolo sagrado"],
    },
    initialItems: [
      { name: "Maça Estrela", quantity: 1, description: "Arma sagrada de impacto e perfuração." },
      { name: "Símbolo Sagrado Entalhado", quantity: 1, description: "Foco de conjuração divina." },
      { name: "Armadura de Couro Batido", quantity: 1, description: "Proteção leve de couro reforçado." },
      { name: "Kit de Primeiros Socorros", quantity: 1, description: "Bandagens, unguentos e talas para tratar ferimentos." },
    ],
    levels: generateLevels(8, true, "empatia", {
      1: ["Doutrina Divina", "Canalização Divina (Cura/Dano)", "Magia Divina"],
      2: ["Talento de Clérigo"],
      3: ["Magias de 2º Círculo", "Canalização Aprimorada"],
      5: ["Magias de 3º Círculo", "Especialista em Conjuração"],
      7: ["Magias de 4º Círculo", "Mestre em Vontade"],
      9: ["Magias de 5º Círculo", "Milagre Menor"],
      11: ["Magias de 6º Círculo", "Mestre em Conjuração Divina"],
      13: ["Magias de 7º Círculo", "Armas Divinas Especialistas"],
      15: ["Magias de 8º Círculo", "Graça Divina Plena"],
      17: ["Magias de 9º Círculo", "Milagre Superior"],
      19: ["Magias de 10º Círculo / Conjurador Divino Lendário"],
    }),
  },
  {
    key: "druid",
    name: "Druid",
    keyAttribute: "empatia",
    hpPerLevel: 8,
    description: "Guardião da natureza e do equilíbrio ecológico. Molda os elementos, conjura a fúria das tempestades e transforma-se em feras selvagens.",
    proficiencies: {
      weapons: ["Armas simples", "Lança", "Cajado", "Foice", "Clava"],
      armor: ["Armadura leve", "Armadura média", "Escudos (não-metálicos)", "Defesa sem armadura"],
      languages: ["Comum", "Druídico"],
      tools: ["Bolsa de ervas"],
    },
    initialItems: [
      { name: "Cajado de Carvalho", quantity: 1, description: "Cajado entalhado com runas naturais." },
      { name: "Armadura de Couro Rústico", quantity: 1, description: "Armadura natural flexível." },
      { name: "Escudo de Madeira Reforçado", quantity: 1, description: "Escudo feito de troncos entrelaçados." },
      { name: "Bolsa de Sementes e Ervas", quantity: 1, description: "Reagentes druídicos." },
    ],
    levels: generateLevels(8, true, "empatia", {
      1: ["Ordem Druídica", "Magia Primal", "Anatema & Juramento"],
      2: ["Talento de Druida"],
      3: ["Magias de 2º Círculo", "Comunhão Selvagem"],
      5: ["Magias de 3º Círculo", "Forma Selvagem Aprimorada"],
      7: ["Magias de 4º Círculo", "Especialista em Conjuração Primal"],
      9: ["Magias de 5º Círculo", "Guardião da Natureza"],
      11: ["Magias de 6º Círculo", "Mestre em Fortitude"],
      13: ["Magias de 7º Círculo", "Forma Elemental"],
      15: ["Magias de 8º Círculo", "Mestre em Conjuração Primal"],
      17: ["Magias de 9º Círculo", "Avatar da Terra"],
      19: ["Magias de 10º Círculo / Druida Lendário"],
    }),
  },
  {
    key: "fighter",
    name: "Fighter",
    keyAttribute: "forca",
    hpPerLevel: 10,
    description: "Mestre incomparável de todas as armas e técnicas marciais. Combina reflexos aguçados, versatilidade tática e precisão devastadora em combate.",
    proficiencies: {
      weapons: ["Armas simples", "Armas marciais", "Armas avançadas", "Ataques desarmados"],
      armor: ["Todas as armaduras (Leve, Média, Pesada)", "Escudos", "Defesa sem armadura"],
      languages: ["Comum"],
      tools: ["Kit de manutenção de armas"],
    },
    initialItems: [
      { name: "Montante de Aço", quantity: 1, description: "Espada de duas mãos com excelente alcance e dano." },
      { name: "Arco Composto", quantity: 1, description: "Arco de precisão marcial." },
      { name: "Brunea de Aço", quantity: 1, description: "Armadura média protetora." },
      { name: "Aljava com 20 Flechas", quantity: 1, description: "Munição para o arco." },
    ],
    levels: generateLevels(10, false, "forca", {
      1: ["Ataque de Oportunidade", "Especialista em Armas (Marciais/Simples)"],
      2: ["Talento de Guerreiro"],
      3: ["Especialização em Armadura", "Postura de Batalha"],
      5: ["Mestre em Grupo de Armas Selecionado", "Ataque Crítico"],
      7: ["Mestre de Batalha", "Evasão de Guerreiro"],
      9: ["Especialização de Combatente", "Reflexos de Aço"],
      11: ["Mestre em Armaduras", "Firmeza Marcial"],
      13: ["Lendário em Grupo de Armas Selecionado"],
      15: ["Mestre em Vontade", "Maestria Superior"],
      17: ["Lendário em Armaduras", "Golpe Supremo"],
      19: ["Campeão Supremo de Batalha"],
    }),
  },
  {
    key: "gunslinger",
    name: "Gunslinger",
    keyAttribute: "destreza",
    hpPerLevel: 10,
    description: "Atirador de elite com armas de fogo e bestas. Especialista em recargas rápidas, truques de tiro espetaculares e pontaria letal a distância.",
    proficiencies: {
      weapons: ["Armas de fogo", "Bestas", "Armas simples", "Armas marciais"],
      armor: ["Armadura leve", "Armadura média", "Defesa sem armadura"],
      languages: ["Comum"],
      tools: ["Kit de armeiro", "Pólvora e balas"],
    },
    initialItems: [
      { name: "Pistola de Pederneira", quantity: 1, description: "Arma de fogo portátil de recarga ágil." },
      { name: "Cartucheira com 30 Tiros", quantity: 1, description: "Balas de chumbo e doses de pólvora negra." },
      { name: "Adaga Oculta", quantity: 1, description: "Arma secundária rápida." },
      { name: "Armadura de Couro Reforçada", quantity: 1, description: "Proteção ágil." },
    ],
    levels: generateLevels(10, false, "destreza", {
      1: ["Caminho do Pistoleiro", "Recarga Singular", "Especialista em Armas de Fogo"],
      2: ["Talento de Pistoleiro"],
      3: ["Truques de Tiro", "Reflexos Rápidos"],
      5: ["Mestre em Armas de Fogo e Bestas"],
      7: ["Evasão do Pistoleiro", "Saque Relâmpago"],
      9: ["Especialização com Armas de Fogo"],
      11: ["Mestre em Percepção", "Tiro Certeiro"],
      13: ["Lendário em Armas de Fogo"],
      15: ["Tiro Penetrante", "Mestre em Fortitude"],
      17: ["Disparo Mortal", "Reflexos Lendários"],
      19: ["Lenda das Armas de Fogo"],
    }),
  },
  {
    key: "inventor",
    name: "Inventor",
    keyAttribute: "inteligencia",
    hpPerLevel: 8,
    description: "Engenheiro genial que desenvolve uma inovação revolucionária (arma, armadura ou constructo companheiro) e arrisca sobrecarregar seus limites mecânicos.",
    proficiencies: {
      weapons: ["Armas simples", "Armas marciais"],
      armor: ["Armadura leve", "Armadura média", "Defesa sem armadura", "Escudos"],
      languages: ["Comum"],
      tools: ["Kit de engenharia e artesanato"],
    },
    initialItems: [
      { name: "Inovação Personalizada", quantity: 1, description: "Protótipo mecânico único desenvolvido pelo inventor." },
      { name: "Kit de Ferramentas de Precisão", quantity: 1, description: "Chaves, engrenagens, alicates e soldas." },
      { name: "Balestra Leve", quantity: 1, description: "Arma de disparo mecânica." },
      { name: "Armadura de Couro Cravejado", quantity: 1, description: "Proteção moderada." },
    ],
    levels: generateLevels(8, false, "inteligencia", {
      1: ["Inovação de Inventor", "Sobrecarga (Overdrive)", "Engenhosidade"],
      2: ["Talento de Inventor"],
      3: ["Modificação de Inovação", "Artesão Perito"],
      5: ["Especialista em Armas Marciais", "Sobrecarga Aprimorada"],
      7: ["Inovação Revolucionária", "Evasão Mecânica"],
      9: ["Especialização de Inventor", "Avanço Tecnológico"],
      11: ["Mestre em Engenharia", "Sobrecarga Mestre"],
      13: ["Inovação Triunfante", "Armaduras Especialista"],
      15: ["Gênio da Mecânica", "Modificação Dupla"],
      17: ["Inovação Lendária", "Sobrecarga Crítica"],
      19: ["Obra-Prima Mecânica"],
    }),
  },
  {
    key: "investigator",
    name: "Investigator",
    keyAttribute: "inteligencia",
    hpPerLevel: 8,
    description: "Detetive brilhante que desvenda mistérios insolúveis e antecipa o desfecho do combate através de dedução lógica e ataques estratégicos calculados.",
    proficiencies: {
      weapons: ["Armas simples", "Armas marciais leves (Arco curto, Rapieira, Espada curta)"],
      armor: ["Armadura leve", "Defesa sem armadura"],
      languages: ["Comum"],
      tools: ["Kit forense / Lupa"],
    },
    initialItems: [
      { name: "Rapieira Fina", quantity: 1, description: "Arma perfurante precisa para ataques calculados." },
      { name: "Lupa de Investigação", quantity: 1, description: "Instrumento óptico para examinar pistas minúsculas." },
      { name: "Caderno de Anotações e Tinta", quantity: 1, description: "Para registrar pistas e deduções." },
      { name: "Armadura de Couro Discreta", quantity: 1, description: "Proteção leve." },
    ],
    levels: generateLevels(8, false, "inteligencia", {
      1: ["Metodologia de Investigação", "Rastrear Pistas", "Estratagema do Investigador"],
      2: ["Talento de Investigador"],
      3: ["Estratagema Aprimorado", "Dedução Rápida"],
      5: ["Especialista em Armas", "Ataque Estratégico +2d6"],
      7: ["Mestre em Percepção", "Evasão de Detetive"],
      9: ["Especialização de Investigador", "Ataque Estratégico +3d6"],
      11: ["Olho Clínico Mestre", "Mestre em Vontade"],
      13: ["Conhecimento Enciclopédico", "Ataque Estratégico +4d6"],
      15: ["Dedução Instantânea", "Mestre em Reflexos"],
      17: ["Mente Brilhante", "Ataque Estratégico +5d6"],
      19: ["Detetive Supremo"],
    }),
  },
  {
    key: "kineticist",
    name: "Kineticist",
    keyAttribute: "vigor",
    hpPerLevel: 8,
    description: "Canalizador físico da matéria e energia elemental (Fogo, Água, Terra, Ar, Madeira, Metal). Molda rajadas cinéticas contínuas e portais dos planos elementais.",
    proficiencies: {
      weapons: ["Armas simples", "Rajada Cinética"],
      armor: ["Armadura leve", "Defesa sem armadura", "Escudos"],
      languages: ["Comum", "Elemental"],
      tools: [],
    },
    initialItems: [
      { name: "Foco Cinético", quantity: 1, description: "Gema ou talismã canalizador dos portais elementais." },
      { name: "Adaga de Defesa", quantity: 1, description: "Arma simples de reserva." },
      { name: "Armadura de Couro Leve", quantity: 1, description: "Traje flexível para canalização." },
      { name: "Mochila de Viagem", quantity: 1, description: "Provisões e cantil." },
    ],
    levels: generateLevels(8, false, "vigor", {
      1: ["Portal Cinético (Elemental Gate)", "Rajada Cinética (Kinetic Blast)", "Canalização de Impulsos"],
      2: ["Talento de Cinético"],
      3: ["Expansão de Portal", "Impulso Aprimorado"],
      5: ["Especialista em Impulsos Cinéticos", "Aura Elemental"],
      7: ["Junção Elemental", "Evasão Elemental"],
      9: ["Especialização Cinética", "Impulso Mestre"],
      11: ["Mestre em Fortitude", "Portal Fluido"],
      13: ["Especialização Superior", "Aura Cinética Mestre"],
      15: ["Mestre em Impulsos Cinéticos", "Fim do Dreno"],
      17: ["Lendário em Impulsos Cinéticos", "Conjunção dos Planos"],
      19: ["Avatar Elemental Supremo"],
    }),
  },
  {
    key: "magus",
    name: "Magus",
    keyAttribute: "inteligencia",
    hpPerLevel: 8,
    description: "Guerreiro arcano que une feitiçaria e esgrima em um estilo de luta simbiótico, canalizando magias de destruição através do fio de sua lâmina no Spellstrike.",
    proficiencies: {
      weapons: ["Armas simples", "Armas marciais"],
      armor: ["Armadura leve", "Armadura média", "Defesa sem armadura", "Escudos"],
      languages: ["Comum"],
      tools: ["Livro de magias"],
    },
    initialItems: [
      { name: "Espada Larga Rúnica", quantity: 1, description: "Arma condutora para o Spellstrike." },
      { name: "Livro de Magias do Magus", quantity: 1, description: "Tomo de feitiços arcanos de combate." },
      { name: "Brunea de Couro Reforçado", quantity: 1, description: "Armadura equilibrada para conjuração e combate." },
      { name: "Bolsa de Componentes Arcanos", quantity: 1, description: "Reagentes para magias." },
    ],
    levels: generateLevels(8, true, "inteligencia", {
      1: ["Golpe Mágico (Spellstrike)", "Cascata Arcana (Arcane Cascade)", "Magia Arcana"],
      2: ["Talento de Magus"],
      3: ["Magias de 2º Círculo", "Sintonia de Batalha"],
      5: ["Magias de 3º Círculo", "Especialista em Armas Marciais"],
      7: ["Magias de 4º Círculo", "Especialista em Conjuração Arcana"],
      9: ["Magias de 5º Círculo", "Spellstrike Aprimorado"],
      11: ["Magias de 6º Círculo", "Mestre em Fortitude"],
      13: ["Magias de 7º Círculo", "Armaduras Especialista"],
      15: ["Magias de 8º Círculo", "Mestre em Conjuração Arcana"],
      17: ["Magias de 9º Círculo", "Cascata Suprema"],
      19: ["Vértice do Guerreiro Mágico"],
    }),
  },
  {
    key: "monk",
    name: "Monk",
    keyAttribute: "destreza",
    hpPerLevel: 10,
    description: "Mestre das artes marciais e disciplina interior do Ki. Desfere sequências de golpes desarmados letais com velocidade espantosa e mobilidade acrobática.",
    proficiencies: {
      weapons: ["Armas simples", "Armas de monge", "Ataques desarmados poderosos"],
      armor: ["Defesa sem armadura (Especialista inicial)"],
      languages: ["Comum"],
      tools: [],
    },
    initialItems: [
      { name: "Vestes de Seda de Treinamento", quantity: 1, description: "Vestimentas leves que permitem total liberdade de movimentos." },
      { name: "Bastão Bo de Madeira Nobre", quantity: 1, description: "Arma tradicional de monge." },
      { name: "Shurikens de Aço", quantity: 5, description: "Armas de arremesso silenciosas." },
      { name: "Contas de Meditação Ki", quantity: 1, description: "Foco interior para concentração espiritual." },
    ],
    levels: generateLevels(10, true, "destreza", {
      1: ["Rajada de Golpes (Flurry of Blows)", "Punho Poderoso", "Movimento Místico (+3m)"],
      2: ["Talento de Monge"],
      3: ["Movimento Místico (+6m)", "Evasão de Monge"],
      5: ["Especialista em Ataques Desarmados", "Golpes Críticos"],
      7: ["Mestre em Defesa sem Armadura", "Caminho do Ki"],
      9: ["Especialização de Monge", "Reflexos de Raio"],
      11: ["Mestre em Fortitude", "Movimento Místico (+9m)"],
      13: ["Mestre em Ataques Desarmados", "Corpo Diamantino"],
      15: ["Lendário em Defesa sem Armadura", "Mestre em Vontade"],
      17: ["Golpe Devastador", "Movimento Místico (+12m)"],
      19: ["Lendário em Ataques Desarmados / Mestre da Perfeição"],
    }),
  },
  {
    key: "oracle",
    name: "Oracle",
    keyAttribute: "empatia",
    hpPerLevel: 8,
    description: "Vidente tocado por forças cósmicas avassaladoras. Porta uma Maldição Divina que debilita seu corpo enquanto liberta poderes miraculosos avassaladores.",
    proficiencies: {
      weapons: ["Armas simples"],
      armor: ["Armadura leve", "Defesa sem armadura"],
      languages: ["Comum"],
      tools: ["Foco oracular"],
    },
    initialItems: [
      { name: "Cetro Oracular", quantity: 1, description: "Cetro entalhado com representações do mistério cósmico." },
      { name: "Túnica com Runas Astrais", quantity: 1, description: "Vestes imbuídas com energia oracular." },
      { name: "Adaga de Prata Cerimonial", quantity: 1, description: "Para rituais e defesa básica." },
      { name: "Bolsa de Incensos Místicos", quantity: 1, description: "Para entrar em transe profético." },
    ],
    levels: generateLevels(8, true, "empatia", {
      1: ["Mistério do Oráculo", "Maldição do Oráculo", "Magia Divina Espontânea"],
      2: ["Talento de Oráculo"],
      3: ["Magias de 2º Círculo", "Maldição Maior"],
      5: ["Magias de 3º Círculo", "Especialista em Conjuração Divina"],
      7: ["Magias de 4º Círculo", "Revelação Cósmica"],
      9: ["Magias de 5º Círculo", "Mestre em Vontade"],
      11: ["Magias de 6º Círculo", "Maldição Extrema"],
      13: ["Magias de 7º Círculo", "Especialização de Oráculo"],
      15: ["Magias de 8º Círculo", "Mestre em Conjuração Divina"],
      17: ["Magias de 9º Círculo", "Apoteose Profética"],
      19: ["Magias de 10º Círculo / Conjurador Oracular Lendário"],
    }),
  },
  {
    key: "psychic",
    name: "Psychic",
    keyAttribute: "inteligencia",
    hpPerLevel: 6,
    description: "Mente prodigiosa capaz de dobrar a realidade por pura força mental. Amplifica truques mentais ao entrar em estados de transe psíquico (Unleash Psyche).",
    proficiencies: {
      weapons: ["Armas simples"],
      armor: ["Defesa sem armadura"],
      languages: ["Comum"],
      tools: ["Ampulheta ou Foco Psíquico"],
    },
    initialItems: [
      { name: "Cristal Psíquico Ressonante", quantity: 1, description: "Cristal que amplifica vibrações mentais." },
      { name: "Vestes Acadêmicas Confortáveis", quantity: 1, description: "Roupas leves que auxiliam a concentração." },
      { name: "Adaga de Bolso", quantity: 1, description: "Arma de último recurso." },
      { name: "Diário de Pesquisa Psíquica", quantity: 1, description: "Mapas mentais e registros telecinéticos." },
    ],
    levels: generateLevels(6, true, "inteligencia", {
      1: ["Libertar a Psique (Unleash Psyche)", "Mente Consciente & Inconsciente", "Magia Oculta Espontânea"],
      2: ["Talento de Psíquico"],
      3: ["Magias de 2º Círculo", "Truques Psíquicos Amplificados"],
      5: ["Magias de 3º Círculo", "Especialista em Conjuração Oculta"],
      7: ["Magias de 4º Círculo", "Ondas Mentais Aprimoradas"],
      9: ["Magias de 5º Círculo", "Mestre em Vontade"],
      11: ["Magias de 6º Círculo", "Clarividência Psíquica"],
      13: ["Magias de 7º Círculo", "Reflexos Mentais"],
      15: ["Magias de 8º Círculo", "Mestre em Conjuração Oculta"],
      17: ["Magias de 9º Círculo", "Domínio Telepático Total"],
      19: ["Magias de 10º Círculo / Mente Lendária Infinita"],
    }),
  },
  {
    key: "ranger",
    name: "Ranger",
    keyAttribute: "destreza",
    hpPerLevel: 10,
    description: "Rastreador e caçador implacável das terras ermas. Marca presas com precisão cirúrgica, ataca de emboscadas e guia companheiros em qualquer terreno.",
    proficiencies: {
      weapons: ["Armas simples", "Armas marciais", "Ataques desarmados"],
      armor: ["Armadura leve", "Armadura média", "Defesa sem armadura", "Escudos"],
      languages: ["Comum"],
      tools: ["Armadilhas", "Kit de sobrevivência"],
    },
    initialItems: [
      { name: "Arco Longo de Caça", quantity: 1, description: "Arco de grande alcance e precisão." },
      { name: "Espadas Curtas Gêmeas", quantity: 2, description: "Par de espadas leves para combate com duas armas." },
      { name: "Armadura de Couro Batido", quantity: 1, description: "Proteção leve e flexível para camuflagem." },
      { name: "Carcás com 30 Flechas", quantity: 1, description: "Munição para caçada." },
    ],
    levels: generateLevels(10, false, "destreza", {
      1: ["Caçar Presa (Hunt Prey)", "Borda do Caçador (Flurry/Precision/Outwit)"],
      2: ["Talento de Patrulheiro"],
      3: ["Passo Firme nas Ermas", "Rastreador Experiente"],
      5: ["Especialista em Armas Marciais", "Mestre de Terreno"],
      7: ["Evasão do Caçador", "Alerta Rápido"],
      9: ["Especialização de Patrulheiro", "Presa Marcada Aprimorada"],
      11: ["Mestre em Fortitude", "Passo Invisível"],
      13: ["Mestre em Armas Marciais", "Armaduras Especialista"],
      15: ["Mestre em Reflexos", "Presa Múltipla"],
      17: ["Mestre Caçador", "Golpe Mortal"],
      19: ["Lenda das Terras Ermas"],
    }),
  },
  {
    key: "rogue",
    name: "Rogue",
    keyAttribute: "destreza",
    hpPerLevel: 8,
    description: "Especialista em infiltração, truques sujos e golpes de oportunidade. Explora fraquezas dos adversários com Ataques Furtivos letais e perícias sem limites.",
    proficiencies: {
      weapons: ["Armas simples", "Espada curta", "Rapieira", "Arco curto", "Clube"],
      armor: ["Armadura leve", "Defesa sem armadura"],
      languages: ["Comum", "Gíria de Ladrão"],
      tools: ["Ferramentas de ladrão (gazúas)"],
    },
    initialItems: [
      { name: "Rapieira de Duelo", quantity: 1, description: "Lâmina ágil perfeita para ataques furtivos." },
      { name: "Adagas de Arremesso", quantity: 3, description: "Adagas equilibradas para ataque à queima-roupa ou arremesso." },
      { name: "Gazúas de Aço Profissionais", quantity: 1, description: "Conjunto para desarmar armadilhas e abrir fechaduras." },
      { name: "Armadura de Couro Escuro", quantity: 1, description: "Camuflagem em sombras." },
    ],
    levels: generateLevels(8, false, "destreza", {
      1: ["Ataque Furtivo (+1d6)", "Artimanha do Ladino (Racket)", "Surpresa Ladina"],
      2: ["Talento de Ladino"],
      3: ["Denegação de Destreza", "Aumento de Perícia Duplo"],
      5: ["Especialista em Armas", "Ataque Furtivo (+2d6)"],
      7: ["Evasão Suprema", "Mestre em Percepção"],
      9: ["Debilitações de Ataque", "Ataque Furtivo (+3d6)"],
      11: ["Mestre em Reflexos", "Mestre em Gazúas"],
      13: ["Mestre em Armas Simples e Ágeis", "Ataque Furtivo (+4d6)"],
      15: ["Debilitação Maior", "Mestre em Vontade"],
      17: ["Ataque Furtivo (+5d6)", "Mestre das Sombras"],
      19: ["Ladino Lendário / Golpe Mortal Silencioso"],
    }),
  },
  {
    key: "sorcerer",
    name: "Sorcerer",
    keyAttribute: "empatia",
    hpPerLevel: 6,
    description: "Conjurador com magia inata pulsando em suas veias herdada de linhagens místicas (dracônica, angelical, demoníaca, fada ou aberrante).",
    proficiencies: {
      weapons: ["Armas simples"],
      armor: ["Defesa sem armadura"],
      languages: ["Comum"],
      tools: [],
    },
    initialItems: [
      { name: "Bordão com Cristal Incrustado", quantity: 1, description: "Cajado simples para canalização mágica." },
      { name: "Adaga Elegante", quantity: 1, description: "Arma leve cerimonial." },
      { name: "Manto de Tecido Nobre", quantity: 1, description: "Vestes com símbolos da linhagem sanguínea." },
      { name: "Bolsa de Reagentes de Linhagem", quantity: 1, description: "Escamas, penas ou essências místicas." },
    ],
    levels: generateLevels(6, true, "empatia", {
      1: ["Linhagem de Sangue (Bloodline)", "Magia Espontânea", "Magia da Linhagem"],
      2: ["Talento de Feiticeiro"],
      3: ["Magias de 2º Círculo", "Poder Sanguíneo Menor"],
      5: ["Magias de 3º Círculo", "Especialista em Conjuração"],
      7: ["Magias de 4º Círculo", "Poder Sanguíneo Maior"],
      9: ["Magias de 5º Círculo", "Mestre em Vontade"],
      11: ["Magias de 6º Círculo", "Erupção Mágica da Linhagem"],
      13: ["Magias de 7º Círculo", "Especialização Mágica"],
      15: ["Magias de 8º Círculo", "Mestre em Conjuração"],
      17: ["Magias de 9º Círculo", "Avatar da Linhagem de Sangue"],
      19: ["Magias de 10º Círculo / Feiticeiro Lendário"],
    }),
  },
  {
    key: "summoner",
    name: "Summoner",
    keyAttribute: "empatia",
    hpPerLevel: 10,
    description: "Convocador ligado por um elo místico inquebrável a um Eidolon companheiro manifestado diretamente de outros planos para lutar em perfeita sincronia.",
    proficiencies: {
      weapons: ["Armas simples"],
      armor: ["Defesa sem armadura"],
      languages: ["Comum"],
      tools: [],
    },
    initialItems: [
      { name: "Talismã do Elo Espiritual", quantity: 1, description: "Canalizador da conexão simbiótica com o Eidolon." },
      { name: "Lança Leve", quantity: 1, description: "Arma simples de alcance." },
      { name: "Túnica de Convocador", quantity: 1, description: "Vestimentas com runas de convocação." },
      { name: "Kit de Acampamento", quantity: 1, description: "Provisões para o mestre e a criatura." },
    ],
    levels: generateLevels(10, true, "empatia", {
      1: ["Manifestar Eidolon", "Ato Uno (Act Together)", "Pontos de Vida Compartilhados"],
      2: ["Talento de Convocador"],
      3: ["Magias de 2º Círculo", "Evolução Menor do Eidolon"],
      5: ["Magias de 3º Círculo", "Especialista em Ataques do Eidolon"],
      7: ["Magias de 4º Círculo", "Transposição Espiritual"],
      9: ["Magias de 5º Círculo", "Mestre em Vontade"],
      11: ["Magias de 6º Círculo", "Evolução Superior"],
      13: ["Magias de 7º Círculo", "Defesa Simbiótica"],
      15: ["Magias de 8º Círculo", "Mestre em Conjuração"],
      17: ["Magias de 9º Círculo", "Fusão de Eidolon"],
      19: ["Elo Perfeito / Convocador Lendário"],
    }),
  },
  {
    key: "swashbuckler",
    name: "Swashbuckler",
    keyAttribute: "destreza",
    hpPerLevel: 10,
    description: "Duelista acrobata e audacioso que transforma acrobacias ousadas em 'Panache', finalizando oponentes com finalizadores espetaculares (Finishers).",
    proficiencies: {
      weapons: ["Armas simples", "Armas marciais ágeis/acrobáticas (Rapieira, Florete, Adaga, Chicote)"],
      armor: ["Armadura leve", "Defesa sem armadura", "Escudos"],
      languages: ["Comum"],
      tools: [],
    },
    initialItems: [
      { name: "Florete Elegante de Duelo", quantity: 1, description: "Espada fina com guarda intrincada." },
      { name: "Capa Elegante com Forro de Seda", quantity: 1, description: "Acessório para fintas e distrações no combate." },
      { name: "Adaga Canhota", quantity: 1, description: "Para aparar ataques e contragolpes." },
      { name: "Armadura de Couro Fino", quantity: 1, description: "Proteção ágil." },
    ],
    levels: generateLevels(10, false, "destreza", {
      1: ["Panache & Estilo de Espadachim", "Finalizador Confiante (Finisher)", "Acrobacia Ousada"],
      2: ["Talento de Espadachim"],
      3: ["Finalizador Preciso", "Movimento Rápido (+3m)"],
      5: ["Especialista em Armas Marciais", "Finalizador +2d6"],
      7: ["Evasão do Espadachim", "Panache Infatigável"],
      9: ["Especialização de Espadachim", "Finalizador +3d6"],
      11: ["Mestre em Reflexos", "Riposte Elegante"],
      13: ["Mestre em Armas Marciais", "Finalizador +4d6"],
      15: ["Mestre em Vontade", "Panache Lendário"],
      17: ["Finalizador Mortal (+5d6)", "Reflexos Impossíveis"],
      19: ["Lenda dos Duelos Acrobáticos"],
    }),
  },
  {
    key: "thaumaturge",
    name: "Thaumaturge",
    keyAttribute: "empatia",
    hpPerLevel: 8,
    description: "Erudito do oculto que carrega implementos mágicos esotéricos (espelho, amuleto, cálice, lanterna, sino) e explora vulnerabilidades místicas em qualquer criatura.",
    proficiencies: {
      weapons: ["Armas simples", "Armas marciais"],
      armor: ["Armadura leve", "Armadura média", "Defesa sem armadura", "Escudos"],
      languages: ["Comum", "Oculto"],
      tools: ["Implementos esotéricos"],
    },
    initialItems: [
      { name: "Implemento de Taumaturgo (Amuleto/Espelho)", quantity: 1, description: "Relíquia esotérica canalizadora de poderes ocultos." },
      { name: "Espada Curta Cerimonial", quantity: 1, description: "Arma com símbolos esotéricos entalhados." },
      { name: "Armadura de Couro Cravejado", quantity: 1, description: "Proteção média." },
      { name: "Bolsa de Relíquias e Simpatias", quantity: 1, description: "Ossos, pós, pós de ferro e espelhos para explorar fraquezas." },
    ],
    levels: generateLevels(8, false, "empatia", {
      1: ["Explorar Vulnerabilidade (Exploit Vulnerability)", "Primeiro Implemento", "Simpatia Esotérica"],
      2: ["Talento de Taumaturgo"],
      3: ["Especialista em Ocultismo", "Implemento Aprimorado"],
      5: ["Segundo Implemento", "Especialista em Armas Marciais"],
      7: ["Evasão de Taumaturgo", "Vulnerabilidade Pessoal"],
      9: ["Especialização de Taumaturgo", "Implemento Experiente"],
      11: ["Mestre em Vontade", "Análise Rápida de Fraquezas"],
      13: ["Mestre em Armas Marciais", "Implemento Maior"],
      15: ["Terceiro Implemento", "Mestre em Fortitude"],
      17: ["Implemento Paragon", "Exploração Letal"],
      19: ["Mestre Supremo do Oculto"],
    }),
  },
  {
    key: "witch",
    name: "Witch",
    keyAttribute: "inteligencia",
    hpPerLevel: 6,
    description: "Conjuradora que forja um pacto com um Patrono misterioso, ensinando feitiços ancestrais e truques de maldição através de um Familiar Mágico falante.",
    proficiencies: {
      weapons: ["Armas simples"],
      armor: ["Defesa sem armadura"],
      languages: ["Comum"],
      tools: ["Caldeirão / Tomo de feitiços"],
    },
    initialItems: [
      { name: "Familiar Mágico (Corvo, Gato ou Serpente)", quantity: 1, description: "Criatura mística companheira que guarda as magias da bruxa." },
      { name: "Caldeirão de Ferro Pequeno", quantity: 1, description: "Para preparar pós e misturas rituais." },
      { name: "Foice Pequena de Colheita", quantity: 1, description: "Para colher ingredientes e defesa pessoal." },
      { name: "Manto das Sombras com Capuz", quantity: 1, description: "Roupas tradicionais de bruxaria." },
    ],
    levels: generateLevels(6, true, "inteligencia", {
      1: ["Patrono da Bruxa", "Familiar Mágico Guardião", "Feitiços de Maldição (Hexes)"],
      2: ["Talento de Bruxa"],
      3: ["Magias de 2º Círculo", "Familiar Aprimorado"],
      5: ["Magias de 3º Círculo", "Especialista em Conjuração"],
      7: ["Magias de 4º Círculo", "Hex Maior"],
      9: ["Magias de 5º Círculo", "Mestre em Vontade"],
      11: ["Magias de 6º Círculo", "Comunhão com Patrono"],
      13: ["Magias de 7º Círculo", "Especialização Mágica"],
      15: ["Magias de 8º Círculo", "Mestre em Conjuração"],
      17: ["Magias de 9º Círculo", "Hex Lendário"],
      19: ["Magias de 10º Círculo / Bruxa Suprema"],
    }),
  },
  {
    key: "wizard",
    name: "Wizard",
    keyAttribute: "inteligencia",
    hpPerLevel: 6,
    description: "Estudioso supremo das leis arcanas do cosmos. Prepara feitiços complexos através de rigoroso estudo metódico de seu grimório pessoal.",
    proficiencies: {
      weapons: ["Armas simples (Bordão, Adaga, Besta leve)"],
      armor: ["Defesa sem armadura"],
      languages: ["Comum", "Dracônico"],
      tools: ["Grimório / Livro de Magias"],
    },
    initialItems: [
      { name: "Grimório Arcano Encadernado em Couro", quantity: 1, description: "Livro de feitiços manuscrito contendo a biblioteca de magias do mago." },
      { name: "Bordão de Madeira de Carvalho", quantity: 1, description: "Foco arcano clássico." },
      { name: "Adaga Cerimonial", quantity: 1, description: "Para rituais e defesa de emergência." },
      { name: "Bolsa de Componentes Arcanos e Tinta Mágica", quantity: 1, description: "Pós raros e tinta alquímica para transcrever novos feitiços." },
    ],
    levels: generateLevels(6, true, "inteligencia", {
      1: ["Escola de Magia Arcana", "Tese Arcana", "Grimório de Feitiços", "Conjuração Arcana Preparada"],
      2: ["Talento de Mago"],
      3: ["Magias de 2º Círculo", "Dreno de Foco Arcano"],
      5: ["Magias de 3º Círculo", "Especialista em Conjuração Arcana"],
      7: ["Magias de 4º Círculo", "Mestre em Vontade"],
      9: ["Magias de 5º Círculo", "Descoberta Arcana"],
      11: ["Magias de 6º Círculo", "Mestre em Conjuração Arcana"],
      13: ["Magias de 7º Círculo", "Especialização em Feitiçaria"],
      15: ["Magias de 8º Círculo", "Mestre de Grimório"],
      17: ["Magias de 9º Círculo", "Poder Arcano Supremo"],
      19: ["Magias de 10º Círculo / Arquimago Lendário"],
    }),
  },
];
